version: 1
AppDir:
  path: /root/assfonts/AppDir
  app_info:
    id: assfonts-gui
    name: assfonts-gui
    icon: icon
    version: !!!VERSION!!!
    exec: usr/bin/assfonts-gui
    exec_args: $@
  apt:
    arch:
    - armhf
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy main restricted
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy universe
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy-updates universe
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy multiverse
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy-updates multiverse
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted
        universe multiverse
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy-security universe
    - sourceline: deb http://ports.ubuntu.com/ubuntu-ports jammy-security multiverse
    include:
    - libc-bin
    - libcap2:armhf
    - libdbus-1-3:armhf
    - libgcc-s1:armhf
    - libgpg-error0:armhf
    - liblzma5:armhf
  files:
    include:
    - /lib/arm-linux-gnueabihf/libGLX.so.0
    - /lib/arm-linux-gnueabihf/libOpenGL.so.0
    - /lib/arm-linux-gnueabihf/libXrender.so.1
    - /lib/arm-linux-gnueabihf/libstdc++.so.6
    - /lib/arm-linux-gnueabihf/libxcb-cursor.so.0
    - /lib/arm-linux-gnueabihf/libxcb-icccm.so.4
    - /lib/arm-linux-gnueabihf/libxcb-keysyms.so.1
    - /lib/arm-linux-gnueabihf/libxcb-randr.so.0
    - /lib/arm-linux-gnueabihf/libxcb-sync.so.1
    - /lib/arm-linux-gnueabihf/libxcb-xinput.so.0
    - /lib/arm-linux-gnueabihf/libxkbcommon-x11.so.0
    exclude:
    - usr/share/man
  runtime:
    env:
      QT_AUTO_SCREEN_SCALE_FACTOR: '1'
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
AppImage:
  arch: armhf
  comp: xz
  update-information: gh-releases-zsync|wyzdwdz|assfonts|latest|assfonts-gui-*-armhf-Linux.AppImage.zsync
  file_name: 'assfonts-gui-!!!VERSION!!!-armhf-Linux.AppImage'