version: 1
AppDir:
  path: /root/assfonts/AppDir
  app_info:
    id: assfonts-gui
    name: assfonts-gui
    icon: icon
    version: !!!VERSION!!!
    exec: usr/bin/assfonts-gui
    exec_args: $@
  apt:
    arch:
    - i386
    allow_unauthenticated: true
    sources: 
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy main restricted
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy universe
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy-updates universe
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy multiverse
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy-updates multiverse
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted
        universe multiverse
    - sourceline: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted
    - sourceline: deb http://security.ubuntu.com/ubuntu/ jammy-security universe
    - sourceline: deb http://security.ubuntu.com/ubuntu/ jammy-security multiverse
    include:
    - libc-bin
    - libcap2:i386
    - libdbus-1-3:i386
    - libgcc-s1:i386
    - libgpg-error0:i386
    - liblzma5:i386
  files:
    include:
    - /lib/i386-linux-gnu/libGLX.so.0
    - /lib/i386-linux-gnu/libOpenGL.so.0
    - /lib/i386-linux-gnu/libXrender.so.1
    - /lib/i386-linux-gnu/libstdc++.so.6
    - /lib/i386-linux-gnu/libxcb-cursor.so.0
    - /lib/i386-linux-gnu/libxcb-icccm.so.4
    - /lib/i386-linux-gnu/libxcb-keysyms.so.1
    - /lib/i386-linux-gnu/libxcb-randr.so.0
    - /lib/i386-linux-gnu/libxcb-sync.so.1
    - /lib/i386-linux-gnu/libxcb-xinput.so.0
    - /lib/i386-linux-gnu/libxkbcommon-x11.so.0
    exclude:
    - usr/share/man
  runtime:
    env:
      QT_AUTO_SCREEN_SCALE_FACTOR: '1'
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
    centos-7:
      command: ./AppRun
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
AppImage:
  arch: i686
  comp: xz
  update-information: gh-releases-zsync|wyzdwdz|assfonts|latest|assfonts-gui-*-i686-Linux.AppImage.zsync
  file_name: 'assfonts-gui-!!!VERSION!!!-i686-Linux.AppImage'