#!/bin/bash

APPDIR=$(dirname "$(readlink -f "$0")")

export PATH="$APPDIR/usr/bin:$PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"
export QT_AUTO_SCREEN_SCALE_FACTOR=1

if [ "$XDG_SESSION_TYPE" = "x11" ]; then
    QT_QPA_PLATFORM=xcb
elif [ -n "$WAYLAND_DISPLAY" ]; then
    QT_QPA_PLATFORM=wayland
fi

if grep -q "XKBOPTIONS.*compose:" /etc/default/keyboard; then
    export QT_IM_MODULE=compose
elif [ "$(ibus version)" ]; then
    export QT_IM_MODULE=ibus
elif [ "$(fcitx-diagnose)" ]; then
    export QT_IM_MODULE=fcitx
fi

export FONTCONFIG_PATH=/etc/fonts

exec "$APPDIR/usr/bin/assfonts-gui" "$@"