#!/bin/bash

APPDIR=$(dirname "$(readlink -f "$0")")

export PATH="$APPDIR/usr/bin:$PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"
export QT_QPA_PLATFORM=xcb
export QT_AUTO_SCREEN_SCALE_FACTOR=1

if [ "$(ibus version)" ]; then
    export QT_IM_MODULE=ibus
elif [ "$(fcitx-diagnose)" ]; then
    export QT_IM_MODULE=fcitx-diagnose
elif grep -q "XKBOPTIONS.*compose:" /etc/default/keyboard; then
    export QT_IM_MODULE=compose
fi

export FONTCONFIG_PATH=/etc/fonts

exec "$APPDIR/usr/bin/assfonts-gui" "$@"